# Generated by Django 4.2.3 on 2023-07-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='manufacturer',
        ),
    ]
